"""Vendored FlatBuffers + gRPC bindings for the engine schema (D83).

This subpackage holds the orchestrator's *local* copy of the Python
modules generated by ``flatc --python`` from the engine repo's
``flatbuffers/fbs/*.fbs`` schema. The originals live at
``/root/quantra_refractor/quantraserver/flatbuffers/python/quantra/``;
they are vendored here so the orchestrator's CI is fully
self-contained (no external git fetch, no path dep, no
deploy-cadence coupling between this monorepo and the engine repo —
D2 / D5 spirit).

Regenerate via ``scripts/regen_engine_bindings.sh`` whenever the
engine schema changes (the script copies + import-rewrites in one
pass).

The bindings' internal cross-imports were rewritten at vendor time
from ``from quantra.X import Y`` to
``from quantra_common.engine_client._generated.quantra.X import Y``
so they are first-class modules of this package — no ``sys.path``
prepend, no ``quantra`` top-level pollution. See D83.
"""
