# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

# Union of date grid types.
class DateGrid(object):
    NONE = 0
    TenorGrid = 1
    RangeGrid = 2

def DateGridCreator(unionType, table):
    from quantra_common.engine_client._generated.quantra.RangeGrid import RangeGridT
    from quantra_common.engine_client._generated.quantra.TenorGrid import TenorGridT
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == DateGrid.TenorGrid:
        return TenorGridT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == DateGrid.RangeGrid:
        return RangeGridT.InitFromBuf(table.Bytes, table.Pos)
    return None
