# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

# Equity exercise style payload.
class EquityExercise(object):
    NONE = 0
    EquityEuropeanExercise = 1
    EquityAmericanExercise = 2
    EquityBermudanExercise = 3

def EquityExerciseCreator(unionType, table):
    from quantra_common.engine_client._generated.quantra.EquityAmericanExercise import EquityAmericanExerciseT
    from quantra_common.engine_client._generated.quantra.EquityBermudanExercise import EquityBermudanExerciseT
    from quantra_common.engine_client._generated.quantra.EquityEuropeanExercise import EquityEuropeanExerciseT
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == EquityExercise.EquityEuropeanExercise:
        return EquityEuropeanExerciseT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == EquityExercise.EquityAmericanExercise:
        return EquityAmericanExerciseT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == EquityExercise.EquityBermudanExercise:
        return EquityBermudanExerciseT.InitFromBuf(table.Bytes, table.Pos)
    return None
