# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

# Equity payoff payload.
class EquityPayoff(object):
    NONE = 0
    EquityPlainVanillaPayoff = 1
    EquityCashOrNothingPayoff = 2
    EquityAssetOrNothingPayoff = 3

def EquityPayoffCreator(unionType, table):
    from quantra_common.engine_client._generated.quantra.EquityAssetOrNothingPayoff import EquityAssetOrNothingPayoffT
    from quantra_common.engine_client._generated.quantra.EquityCashOrNothingPayoff import EquityCashOrNothingPayoffT
    from quantra_common.engine_client._generated.quantra.EquityPlainVanillaPayoff import EquityPlainVanillaPayoffT
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == EquityPayoff.EquityPlainVanillaPayoff:
        return EquityPlainVanillaPayoffT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == EquityPayoff.EquityCashOrNothingPayoff:
        return EquityCashOrNothingPayoffT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == EquityPayoff.EquityAssetOrNothingPayoff:
        return EquityAssetOrNothingPayoffT.InitFromBuf(table.Bytes, table.Pos)
    return None
