# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

# Union of cash flow types.
class Flow(object):
    NONE = 0
    FlowInterest = 1
    FlowPastInterest = 2
    FlowNotional = 3

def FlowCreator(unionType, table):
    from quantra_common.engine_client._generated.quantra.FlowInterest import FlowInterestT
    from quantra_common.engine_client._generated.quantra.FlowNotional import FlowNotionalT
    from quantra_common.engine_client._generated.quantra.FlowPastInterest import FlowPastInterestT
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == Flow.FlowInterest:
        return FlowInterestT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Flow.FlowPastInterest:
        return FlowPastInterestT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Flow.FlowNotional:
        return FlowNotionalT.InitFromBuf(table.Bytes, table.Pos)
    return None
