# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

# Union of all supported curve point types.
class Point(object):
    NONE = 0
    DepositHelper = 1
    FRAHelper = 2
    FutureHelper = 3
    SwapHelper = 4
    BondHelper = 5
    OISHelper = 6
    DatedOISHelper = 7
    ZeroRatePoint = 8
    TenorBasisSwapHelper = 9
    FxSwapHelper = 10
    CrossCcyBasisHelper = 11
    DiscountFactorPoint = 12
    ForwardRatePoint = 13

def PointCreator(unionType, table):
    from quantra_common.engine_client._generated.quantra.BondHelper import BondHelperT
    from quantra_common.engine_client._generated.quantra.CrossCcyBasisHelper import CrossCcyBasisHelperT
    from quantra_common.engine_client._generated.quantra.DatedOISHelper import DatedOISHelperT
    from quantra_common.engine_client._generated.quantra.DepositHelper import DepositHelperT
    from quantra_common.engine_client._generated.quantra.DiscountFactorPoint import DiscountFactorPointT
    from quantra_common.engine_client._generated.quantra.FRAHelper import FRAHelperT
    from quantra_common.engine_client._generated.quantra.ForwardRatePoint import ForwardRatePointT
    from quantra_common.engine_client._generated.quantra.FutureHelper import FutureHelperT
    from quantra_common.engine_client._generated.quantra.FxSwapHelper import FxSwapHelperT
    from quantra_common.engine_client._generated.quantra.OISHelper import OISHelperT
    from quantra_common.engine_client._generated.quantra.SwapHelper import SwapHelperT
    from quantra_common.engine_client._generated.quantra.TenorBasisSwapHelper import TenorBasisSwapHelperT
    from quantra_common.engine_client._generated.quantra.ZeroRatePoint import ZeroRatePointT
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == Point.DepositHelper:
        return DepositHelperT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Point.FRAHelper:
        return FRAHelperT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Point.FutureHelper:
        return FutureHelperT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Point.SwapHelper:
        return SwapHelperT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Point.BondHelper:
        return BondHelperT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Point.OISHelper:
        return OISHelperT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Point.DatedOISHelper:
        return DatedOISHelperT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Point.ZeroRatePoint:
        return ZeroRatePointT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Point.TenorBasisSwapHelper:
        return TenorBasisSwapHelperT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Point.FxSwapHelper:
        return FxSwapHelperT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Point.CrossCcyBasisHelper:
        return CrossCcyBasisHelperT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Point.DiscountFactorPoint:
        return DiscountFactorPointT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Point.ForwardRatePoint:
        return ForwardRatePointT.InitFromBuf(table.Bytes, table.Pos)
    return None
