# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

# Union of swaption vol payload types.
class SwaptionVolPayload(object):
    NONE = 0
    SwaptionVolConstantSpec = 1
    SwaptionVolAtmMatrixSpec = 2
    SwaptionVolSmileCubeSpec = 3
    SwaptionSabrParamsSpec = 4
    SwaptionSabrCalibrateSpec = 5

def SwaptionVolPayloadCreator(unionType, table):
    from quantra_common.engine_client._generated.quantra.SwaptionSabrCalibrateSpec import SwaptionSabrCalibrateSpecT
    from quantra_common.engine_client._generated.quantra.SwaptionSabrParamsSpec import SwaptionSabrParamsSpecT
    from quantra_common.engine_client._generated.quantra.SwaptionVolAtmMatrixSpec import SwaptionVolAtmMatrixSpecT
    from quantra_common.engine_client._generated.quantra.SwaptionVolConstantSpec import SwaptionVolConstantSpecT
    from quantra_common.engine_client._generated.quantra.SwaptionVolSmileCubeSpec import SwaptionVolSmileCubeSpecT
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == SwaptionVolPayload.SwaptionVolConstantSpec:
        return SwaptionVolConstantSpecT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == SwaptionVolPayload.SwaptionVolAtmMatrixSpec:
        return SwaptionVolAtmMatrixSpecT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == SwaptionVolPayload.SwaptionVolSmileCubeSpec:
        return SwaptionVolSmileCubeSpecT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == SwaptionVolPayload.SwaptionSabrParamsSpec:
        return SwaptionSabrParamsSpecT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == SwaptionVolPayload.SwaptionSabrCalibrateSpec:
        return SwaptionSabrCalibrateSpecT.InitFromBuf(table.Bytes, table.Pos)
    return None
