"""Pydantic models for the orchestrator's scaffolded endpoints.

Limited to the shapes referenced by ``GET /health`` and the global
exception handlers. Per-product request/response models live in
``pricing/<product>/models.py``.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class HealthResponse(BaseModel):
    """Liveness payload. Never depends on the database or downstream services."""

    status: str = Field(description="Always ``ok`` while the process is serving.")
    service: str = Field(description="Stable service identifier; matches OpenAPI title slug.")
    build_sha: str = Field(description="Build identifier from OrchestratorSettings.")
    env: str = Field(description="Deploy environment label (dev / staging / prod).")


class OrchestratorVersion(BaseModel):
    """The orchestrator's own version and build identifier."""

    version: str = Field(
        description="Orchestrator semantic version; matches the FastAPI app version.",
    )
    build_sha: str = Field(
        description="Build / commit identifier from OrchestratorSettings.",
    )


class EngineVersion(BaseModel):
    """The pricing engine's version. Currently a hardcoded placeholder."""

    version: str = Field(description="Pricing-engine version.")
    source: str = Field(
        description=(
            "Where the engine version came from. ``hardcoded`` means it is a "
            "stopgap constant (pending F3: engine version over gRPC)."
        ),
    )


class VersionResponse(BaseModel):
    """Payload for ``GET /v1/version`` — orchestrator + engine versions.

    Dependency-free (like ``/health``): answers even when the engine, MD
    service, or database are down.
    """

    orchestrator: OrchestratorVersion = Field(description="Orchestrator version info.")
    engine: EngineVersion = Field(description="Pricing-engine version info.")


class WhoamiResponse(BaseModel):
    """Auth-debug payload returned by ``GET /auth/whoami``.

    Carries only the identity bits the calling client needs to confirm
    auth wiring works end-to-end. ``auth_method`` mirrors
    ``AuthContext.auth_type`` (``"firebase"`` | ``"api_key"``). API-key
    metadata such as ``api_key_id`` is intentionally omitted from this
    endpoint to keep the response shape uniform across both auth
    methods; admin / key-management endpoints surface that separately.
    """

    uid: str = Field(description="Firebase UID or API-key owner UID.")
    email: str | None = Field(
        default=None,
        description="Email from the verified token / joined ``app.users`` row.",
    )
    auth_method: str = Field(
        description="One of ``firebase`` or ``api_key``; matches AuthContext.auth_type.",
    )


class ProvisionResponse(BaseModel):
    """The caller's ``app.users`` row, returned by ``POST /auth/provision``.

    Provisioning is the explicit "make my user row exist" step:
    every ``app.*`` entity table FKs ``owner_uid -> app.users.uid``,
    but neither Firebase login nor the dev bypass creates the row, so a
    fresh identity 500s on its first write. Clients (portal post-login,
    the demo seed script) call this once; it is an idempotent upsert.
    """

    uid: str = Field(description="The authenticated caller's UID (row PK).")
    email: str | None = Field(default=None, description="Email on the row, if any.")
    display_name: str | None = Field(default=None, description="Display name on the row, if any.")
    tier: str = Field(description="Account tier; defaults to ``free`` on first create.")


class ErrorResponse(BaseModel):
    """Structured error envelope returned by every global exception handler.

    The contract from is the three core
    fields ``error`` / ``code`` / ``request_id``. ``details`` is an
    optional escape hatch for handlers that want to attach machine-readable
    extra context (the validation handler uses it to surface pydantic
    error objects); it is omitted from the wire payload when ``None``.
    """

    error: str = Field(description="Human-readable summary, safe to surface in clients.")
    code: str = Field(description="Stable machine-readable code, e.g. ``http_404``.")
    request_id: str | None = Field(
        default=None,
        description=(
            "Request ID echoed from the X-Request-Id header (or generated by the "
            "request-id middleware). Lets clients correlate logs."
        ),
    )
    details: list[dict[str, Any]] | None = Field(
        default=None,
        description="Optional structured detail. Populated by the validation handler.",
    )
