"""``GET /v1/traces/{request_id}`` — in-app pricing-trace read.

Returns the orchestrator's per-stage timeline for one pricing call,
ordered by ``ts``. Owner-scoped (invariant #5): only rows owned by the
calling principal are returned, and an id the caller owns no rows for is
a 404 ``trace_not_found`` — never a 403, so the existence of another
user's trace is never acknowledged.

Reads go through the ``app_ro`` engine. Tracing is invisible to
the pricing surface: this endpoint is the ONLY way the captured rows
leave the orchestrator.
"""

from __future__ import annotations

import json
from datetime import datetime
from typing import Any, Final

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine

from quantra_common.auth.context import AuthContext
from quantra_orchestrator.auth.dependencies import get_auth_context
from quantra_orchestrator.data.engines import get_app_ro_engine

TRACE_NOT_FOUND_CODE: Final[str] = "trace_not_found"

router = APIRouter(prefix="/v1/traces", tags=["traces"])

_SELECT_SQL = text(
    "SELECT ts, stage, level, duration_ms, summary, payload "
    "FROM app.pricing_traces "
    "WHERE request_id = :request_id AND owner_uid = :owner_uid "
    "ORDER BY ts ASC, id ASC"
)


class TraceNotFoundError(HTTPException):
    """404 raised when the caller owns no trace rows for ``request_id``.

    Carries the ``code`` class attribute the shared HTTPException handler
    reads so the envelope surfaces ``code="trace_not_found"`` instead
    of the generic ``http_404`` token. 404-not-403 per invariant #5.
    """

    code: Final[str] = TRACE_NOT_FOUND_CODE

    def __init__(self, *, request_id: str) -> None:
        super().__init__(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"No pricing trace found for request_id {request_id!r}.",
        )


class TraceStage(BaseModel):
    """One pipeline stage in a pricing-call timeline.

    ``summary`` is a short plain-English sentence interpreting the
    stage's actual content (summaries) — generated by the shared
    trace helpers where the data lives and surfaced here as a top-level
    field so the investigate screen reads like a story rather than raw
    JSON. ``None`` for legacy rows written before summaries existed.
    """

    ts: datetime
    stage: str
    level: str
    duration_ms: int | None = None
    summary: str | None = None
    payload: Any | None = None


class TraceTimeline(BaseModel):
    """The full ordered stage timeline for one ``request_id``."""

    request_id: str
    stages: list[TraceStage] = Field(default_factory=list)


@router.get(
    "/{request_id}",
    status_code=status.HTTP_200_OK,
    response_model=TraceTimeline,
    summary="Investigate a pricing call by transaction id.",
    description=(
        "Returns the orchestrator's per-stage view of the pricing call "
        "identified by ``request_id`` — inputs, entities loaded, market "
        "data resolved, the assembled engine JSON, the engine's response "
        "or real error, and the history-write outcome. Owner-scoped; "
        "404 ``trace_not_found`` when the caller owns no rows for the id."
    ),
    responses={
        401: {"description": "Missing or invalid credentials."},
        404: {"description": "No trace rows owned by the caller for this id."},
        503: {"description": "Persistent storage not configured."},
    },
)
async def get_trace(
    request_id: str,
    ctx: AuthContext = Depends(get_auth_context),
    ro_engine: AsyncEngine = Depends(get_app_ro_engine),
) -> TraceTimeline:
    async with ro_engine.connect() as conn:
        result = await conn.execute(_SELECT_SQL, {"request_id": request_id, "owner_uid": ctx.uid})
        rows = result.mappings().all()

    if not rows:
        raise TraceNotFoundError(request_id=request_id)

    stages = [
        TraceStage(
            ts=row["ts"],
            stage=row["stage"],
            level=row["level"],
            duration_ms=row["duration_ms"],
            # ``.get`` tolerates legacy rows written before the summary
            # column existed (NULL) without a KeyError.
            summary=row.get("summary"),
            payload=_decode_payload(row["payload"]),
        )
        for row in rows
    ]
    return TraceTimeline(request_id=request_id, stages=stages)


def _decode_payload(value: Any) -> Any:  # noqa: ANN401 -- jsonb round-trips as Any
    """Return the stage payload as a Python object.

    The SQLAlchemy asyncpg dialect decodes JSONB to a Python object, but
    a raw ``str`` (older codec / a fake engine) is tolerated by parsing
    it as JSON; anything else is passed through verbatim.
    """

    if value is None or isinstance(value, dict | list):
        return value
    if isinstance(value, str):
        try:
            return json.loads(value)
        except (TypeError, ValueError):
            return value
    return value


__all__ = [
    "router",
]
